// Generated by listgen. DO NOT EDIT.
// Command: listgen -package stringlist -type string -cmp "if a < b {return -1}; if a > b {return 1}; return 0;"

package stringlist

import (
	"errors"
	"fmt"
	"sync/atomic"
	"unsafe"
)

var (
	ErrValueExists   = errors.New("stringlist: value exists")
	ErrValueNotFound = errors.New("stringlist: value does not exist")
)

type list struct {
	head unsafe.Pointer
	cmp  func(string, string) int
}

type node struct {
	val  string
	next unsafe.Pointer
}

type iterator struct {
	list    *list
	current *node
	valid   bool
}

func cmp(a string, b string) int {
	if a < b {
		return -1
	}
	if a > b {
		return 1
	}
	return 0
}

// NewList returns a lock-free ordered list with values of type string.
func NewList() *list {
	return &list{}
}

// Insert inserts v into the list in order. An error is returned if v is already present.
func (l *list) Insert(v string) error {
	n := &node{
		val:  v,
		next: nil,
	}

HEAD:
	headPtr := atomic.LoadPointer(&l.head)

	if headPtr == nil {
		if !atomic.CompareAndSwapPointer(&l.head, headPtr, unsafe.Pointer(n)) {
			goto HEAD
		}

		return nil
	}

	headNode := (*node)(headPtr)
	if cmp(headNode.val, n.val) > 0 {
		n.next = headPtr
		if !atomic.CompareAndSwapPointer(&l.head, headPtr, unsafe.Pointer(n)) {
			goto HEAD
		}

		return nil
	}

NEXT:
	nextPtr := atomic.LoadPointer(&headNode.next)
	if nextPtr == nil {
		if !atomic.CompareAndSwapPointer(&headNode.next, nextPtr, unsafe.Pointer(n)) {
			goto NEXT
		}

		return nil
	}

	nextNode := (*node)(nextPtr)
	if cmp(nextNode.val, n.val) > 0 {
		n.next = nextPtr
		if !atomic.CompareAndSwapPointer(&headNode.next, nextPtr, unsafe.Pointer(n)) {
			goto NEXT
		}

		return nil
	}

	if cmp(nextNode.val, n.val) == 0 {
		return ErrValueExists
	}

	headNode = nextNode
	goto NEXT
}

// Remove removes v from the list. An error is returned if v is not present.
func (l *list) Remove(v string) error {
HEAD:
	headPtr := atomic.LoadPointer(&l.head)

	if headPtr == nil {
		return ErrValueNotFound
	}

	headNode := (*node)(headPtr)

	if cmp(headNode.val, v) == 0 {
		nextPtr := atomic.LoadPointer(&headNode.next)
		if !atomic.CompareAndSwapPointer(&l.head, headPtr, nextPtr) {
			goto HEAD
		}

		return nil
	}

NEXT:
	nextPtr := atomic.LoadPointer(&headNode.next)
	if nextPtr == nil {
		return ErrValueNotFound
	}

	nextNode := (*node)(nextPtr)

	if cmp(nextNode.val, v) > 0 {
		return ErrValueNotFound
	}

	if cmp(nextNode.val, v) == 0 {
		replacementPtr := atomic.LoadPointer(&nextNode.next)
		if !atomic.CompareAndSwapPointer(&headNode.next, nextPtr, replacementPtr) {
			goto NEXT
		}

		return nil
	}

	headNode = nextNode
	goto NEXT
}

// NewIterator returns a new iterator. Values can be read
// after Next is called.
func (l *list) NewIterator() *iterator {
	return &iterator{
		list:  l,
		valid: true,
	}
}

// Next positions the iterator at the next node in the list.
// Next will be positioned at the head on the first call.
// The return value will be true if a value can be read from the list.
func (i *iterator) Next() bool {
	if !i.valid {
		return false
	}

	if i.current == nil {
		if i.list.head == nil {
			i.valid = false
			return false
		}

		i.current = (*node)(i.list.head)
		return true
	}

	i.current = (*node)(i.current.next)

	i.valid = i.current != nil
	return i.valid
}

// Value reads the value from the current node of the iterator.
// An error is returned if a value cannot be retrieved.
func (i *iterator) Value() (string, error) {
	var v string

	if i.current == nil {
		return v, ErrValueNotFound
	}

	return i.current.val, nil
}

// String returns the string representation of the list.
func (l *list) String() string {
	output := ""

	if l.head == nil {
		return output
	}

	n := (*node)(unsafe.Pointer(l.head))

	for n != nil {
		output += fmt.Sprintf("%v ", n.val)
		n = (*node)(unsafe.Pointer(n.next))
	}

	return output
}
